### ISSUE TITLE
The collision handling is wrong

### ISSUE THREAD

**Issue by realjoenguyen** [ahjwang/messenger-emma#6]
Hi authors, 

Thanks for the great work, 

I've been using your framework and I found one issue in the physical world of Messenger. It is the collision handling in ([https://github.com/ahjwang/py-vgdl ](https://github.com/ahjwang/py-vgdl)) is wrong. 

In other words, the agent dies when it is near the enemy, not when it touches the enemy. Because of the stochastic moving of entities, it's tricky to reproduce the issue. However, I screenshotted one state from the game where this happened:

<img width="534" alt="image" src="https://github.com/ahjwang/messenger-emma/assets/26454297/bf39bc79-a930-4b19-9fde-e06d74ba6dc1">

where 3 is the enemy, 15 is the player (agent). The function `_event_handling` in `py_vgdl` in [here](https://github.com/ahjwang/py-vgdl/blob/fd1198c93efd27cb465c7f0b05e07a6e9cda8cea/vgdl/core.py#LL801C1-L803C48) returns these two entities collide, although they don't. 

The error is because of this check` sprite.rect.collidelistall(others)`, which checks whether two under-the-hood Rectangles of two entities overlap. However, their overlap doesn't necessarily mean they touch each other in the Gridworld coordinate. Their under-the-hood rectangle coordinate are `(3, 11, 2, 2` and `(2, 12, 2, 2)`, and their real gridworld  coordinates are `(1, 5)` and `(1, 6)`, respectively. Obviously, they haven't touched each other yet, because their real coordinates are different.  

So right now, I fixed it by adding the following to the loop of [here](https://github.com/ahjwang/py-vgdl/blob/fd1198c93efd27cb465c7f0b05e07a6e9cda8cea/vgdl/core.py#LL801C1-L803C48) 

```    
                    p1 = rect_to_pos(sprite.rect, self.block_size)
                    p2 = rect_to_pos(other.rect, self.block_size)
                    if p1 != p2:
                        continue
                    # print(p1, p2)
```

where

```
def rect_to_pos(r, block_size):
    return r.left // block_size, r.top // block_size
```

Can you double check this? 
Thank you very much!

Joe

**Comment by ahjwang** [comment]
Hi Joe,

Thanks for bringing this to our attention, and the detailed pointers. This was something we observed during development, but was deemed acceptable since the agent can always learn to avoid dying by staying further away. We forked the original py-vgdl repo to fix a small seeding issue, but otherwise kept the implementation and behaviors the same. I suggest opening an issue with the upstream repository (https://github.com/rubenvereecken/py-vgdl). Since we want future results to be consistent with numbers reported in the literature, we will not be updating the behavior of Messenger. 

Authors
