### ISSUE TITLE
Ask about test-se

### ISSUE THREAD

**Issue by realjoenguyen** [ahjwang/messenger-emma#9]
Hi authors, 

What is the difference between `test-se` and `test` in S2? I can't find this in the paper or in the codebase. 

> The split `test-se` is the state estimation version of the test environment, and is only available on stage 2. 

Can you elaborate what "state-estimation version" of S2 means? 
Thank you,

**Comment by ahjwang** [comment]
Hello, thank you for reaching out. The `se`-version of test has identical object movement dynamics compared to training (which is always one fleeing, one chasing, and one stationary entity). The full test version may have differing movement dynamics (e.g. two fleeing and one chasing, or two chasing and one stationary entity, etc). 

The `se` version may be helpful for debugging, but is otherwise not a variant that is used in the canonical messenger evaluations.
